check eth balance for fees
ElrondNetwork/elrond-eth-bridge pull request #193
Opened 2022-01-12 05:38 UTC by dragos-rebegea

2022-01-12 11:19 UTC, iulianpascalau requested changes

2022-01-12 11:19 UTC, iulianpascalau commented on clients/ethereum/client.go
> +	ethclient                 *ethclient.Client
please remove this. Instead, extend the ClientWrapper interface with the BalanceAt method.

2022-01-12 11:19 UTC, iulianpascalau commented on factory/ethElrondBridgeComponents.go
> +	ethClient, err := ethclient.Dial(ethereumConfigs.NetworkAddress)
not required

2022-01-17 12:07 UTC, iulianpascalau submitted a review, later dismissed

2022-01-17 12:07 UTC, iulianpascalau commented on clients/gasManagement/disabled/disabledGasStation.go
> +	return big.NewInt(0), nil
:+1:

2022-01-17 12:07 UTC, iulianpascalau commented on testsCommon/interactors/blockchainClientStub.go
> +func (bcs *BlockchainClientStub) BalanceAt(ctx context.Context, account common.Address, blockNumber *big.Int) (*big.Int, error) {
missing comment

2022-01-17 12:12 UTC, iulianpascalau submitted a review, later dismissed

2022-01-17 12:15 UTC, sstanculeanu submitted a review, later dismissed

2022-01-17 12:19 UTC, iulianpascalau approved these changes

2022-01-17 12:19 UTC, sstanculeanu approved these changes

2022-01-17 12:24 UTC, merged