Integration tests framework part 1
ElrondNetwork/elrond-eth-bridge pull request #61
Opened 2021-09-28 19:31 UTC by iulianpascalau

- added mock Elrond/Ethereum clients
- added framework for defining "contracts" that will perform mocked functions to be used in different scenarios
- fixed a bug that could cause the relayers to panic

TODO: 
- add more functionality on the erd/eth clients, make them work as expected with the mocked contracts 
- finish first test that will prove the successfully processing of the eth->erd transactions flow
- finish test that will prove the successfully processing of the erd->eth transactions flow
- add more scenarios, use more relayers.

2021-09-29 19:37 UTC, dragos-rebegea approved these changes
:+1:

2021-09-30 12:00 UTC, bogdan-rosianu requested changes

2021-09-30 12:37 UTC, iulianpascalau commented on bridge/elrond/client.go
> +		return 0, errors.New("contract error, unexpected 0 length response data")
done

2021-09-30 12:38 UTC, iulianpascalau commented on integrationTests/mock/accountsMap.go
> +			Nonce:           0,
removed the default initiated fields. Kept only the `address` field.

2021-09-30 12:45 UTC, iulianpascalau commented on integrationTests/mock/accountsMap.go
> +// SetAccount will set the account & contract with the provided value
changed `value` to `values`. Changed to use the address from the provided objects

2021-09-30 12:47 UTC, iulianpascalau commented on integrationTests/mock/accountsMap.go
> +	defer am.mutAccounts.Unlock()
done

2021-09-30 12:47 UTC, iulianpascalau commented on integrationTests/mock/contracts/elrond.go
> +var log = logger.GetOrCreate("integrationTests/mock/constracts")
fixed

2021-09-30 13:16 UTC, iulianpascalau commented on integrationTests/testInitializer.go
> +// Close will close any relayers/clients opened
done

2021-09-30 13:22 UTC, bogdan-rosianu approved these changes

2021-09-30 13:34 UTC, mihaieremia approved these changes

2021-09-30 18:12 UTC, dragos-rebegea approved these changes

2021-10-02 13:55 UTC, mihaieremia approved these changes

2021-10-02 13:59 UTC, merged